project: guitar-practice

  data:
    ear_training:
    guitar_neck:
    images:
    music_spreadsheet:
    music_theory:
    scales:

  ear_training_exercises:
    ear_training:
    ear_training_main:
    interval_training:
    pitch_matching:
    pitch_training:

  fretboard_exercises:
    guitar_fretboard_exercise:

  general_packages:
    general:

  images:

  mp3:

  scales_and_arpeggios:
    game_logic:
    get_data:
    chords_main:
    main:

  main:
